### ISSUE TITLE
Problems when building

### ISSUE THREAD

**Issue by osnersanchez** [CaliStyle/angular2-intercom#79] opened 2018-10-28 00:19 UTC
I have the following problem when building the project
![image](https://user-images.githubusercontent.com/12916793/47610453-b890ad80-da23-11e8-8a5f-108026b4f4a9.png)

I am using the following configuration
ng build --prod --output-hashing=all

This problem occurs when adding --prod

The problem occurs specifically when adding the parameters in IntercomModule.forRoot

![image](https://user-images.githubusercontent.com/12916793/47610495-a8c59900-da24-11e8-9135-b68738826185.png)

This problem does not happen with ng serve, only when building the project, using ng serve runs without problems

this is my package.json:

{
  "name": "fortesza-front",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.10",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.1.10",
    "@angular/compiler": "^6.1.10",
    "@angular/core": "^6.1.10",
    "@angular/flex-layout": "^6.0.0-beta.18",
    "@angular/forms": "^6.1.10",
    "@angular/http": "^6.1.10",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "^6.1.10",
    "@angular/platform-browser-dynamic": "^6.1.10",
    "@angular/router": "^6.1.10",
    "@kolkov/ngx-metrika": "^0.3.2",
    "angulartics2": "^6.2.0",
    "bootstrap": "^4.1.1",
    "chart.js": "^2.7.2",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.7",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "^3.3.1",
    "moment": "^2.22.2",
    "ng-intercom": "^6.0.0-beta.7",
    "ng2-odometer": "^1.1.3",
    "ngx-countdown": "^3.1.0",
    "ngx-toastr": "^9.1.1",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.3.3",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.7.5",
    "@angular/cli": "^6.2.6",
    "@angular/compiler-cli": "^6.1.10",
    "@angular/language-service": "^6.1.10",
    "@types/google.analytics": "0.0.39",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.9.4",
    "codelyzer": "^4.5.0",
    "jasmine-core": "~3.2.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.3",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^1.3.1",
    "protractor": "~5.4.0",
    "ts-node": "~6.2.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  }
}

**Comment by osnersanchez** [comment] 2018-10-28 00:35
Apparently my problem is related to the issue #74

**Comment by wbhob** [comment] 2018-10-28 01:35
Yeah, I'm closing as a dupe of #74.

**Closed as completed by wbhob** 2018-10-28 01:35 UTC

**Comment by swapniltomake** [comment] 2018-11-23 11:33
Same Problem

**Comment by wbhob** [comment] 2018-11-23 17:22
We're still waiting on a PR in #74 @swapniltomake
