### ISSUE TITLE
Error with ng build --prod

### ISSUE THREAD

**Issue by Jatulito** [CaliStyle/angular2-intercom#81] opened 2018-11-15 09:01 UTC
When I try to build prod I get:
ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'IntercomModule' was called.

## Versions:

Angular CLI: 7.0.6
Node: 8.11.3
Angular: 6.0.2
NPM: 5.6.0
ng-intercom: "^7.0.0-beta.0"

app.module.ts:

import { IntercomModule } from 'ng-intercom';
@NgModule({
  imports: [
    CommonModule,
    BrowserAnimationsModule,
    FormsModule,
    RouterModule.forRoot(AppRoutes),
    HttpModule,
    HttpClientModule,
    MaterialModule,
    MatNativeDateModule,
    SidebarModule,
    NavbarModule,
    FooterModule,
    FixedpluginModule,
    BrowserModule,
    ReactiveFormsModule,
    NgbModule,
    AgmCoreModule.forRoot({
      apiKey: environment.googleMapKey
    }),
    IntercomModule.forRoot({
      appId: environment.intercom, // from your Intercom config
      updateOnRouterChange: false // will automatically run `update` on router event changes. Default: `false`
    })    
  ],

app.component.ts:
import { Intercom } from 'ng-intercom';

constructor( private router: Router, public intercom: Intercom, private storeService: StoreService  ) {
  }
ngOnInit() {
 this.intercom.boot({   
            app_id: environment.intercom,       
            name: this.storeService.userName,
            user_id: this.storeService.userId,
              widget: {
                "activator": "#intercom" 
              }
            });
}

Please help

**Comment by wbhob** [comment] 2018-11-15 16:27
We are aware of this issue and lack the resources to fix it. PRs are welcome.

**Comment by wbhob** [comment] 2018-11-16 13:13
Duplicate of #74.

**Closed as completed by wbhob** 2018-11-16 13:13 UTC
