### ISSUE TITLE
Error with ng build --prod

### ISSUE THREAD

**Issue by hassanasad** [CaliStyle/angular2-intercom#40] opened 2018-03-05 07:39 UTC
With version `1.0.0-beta.12` - when `ng build --prod` is called it fails to compile saying:

```
ERROR in Error during template compile of 'CoreModule'
  Function calls are not supported in decorators but 'IntercomModule' was called.
```

P.S: I use a **CoreModule** instead of **AppModule**

**It works fine with `1.0.0-beta.11` though**

```
Angular CLI: 1.7.2
Node: 9.5.0
OS: darwin x64
Angular: 5.2.7
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.7.2
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

**Comment by chrishawn** [comment] 2018-03-05 22:06
not sure if this is related but seems to be:
[https://github.com/angular/angular/issues/14707](https://github.com/angular/angular/issues/14707)

also this as well
[https://github.com/angular/angular-cli/issues/3854](https://github.com/angular/angular-cli/issues/3854)

**Comment by scott-wyatt** [comment] 2018-03-06 00:38
It seems it might be related indeed @chrishawn.  It might also be related to ng-packagr which is now used to output the library. PRs are welcome, I don't think I will be able to get to it until this weekend.

**Comment by chrishawn** [comment] 2018-03-12 16:29
i poked around with it for a little while both options didn't seem to fix it, i think one needs to dig deeper,  also many people having problems with this.

**Comment by KromPass** [comment] 2018-03-22 16:16
I have the same problem.

**Comment by scott-wyatt** [comment] 2018-03-22 20:12
Sorry everyone, I've been busy. This error is being caused by ng-packagr, I'll try and get a fix out for this as soon as possible unless someone beats me to it.

**Comment by scott-wyatt** [comment] 2018-03-25 15:45
Fixed by #42

**Closed as completed by scott-wyatt** 2018-03-25 15:45 UTC
Labels: bug, help wanted

**Comment by eyalhakim** [comment] 2018-10-15 20:55
@scott-wyatt this reproduces now for me in beta.6

**Comment by motcowley** [comment] 2018-10-16 11:21
Also seeing the same problem on 6.0.0-beta.x

**Comment by chrishawn** [comment] 2018-10-16 16:53
yeah it definitely seems to be back

**Comment by timsergeev** [comment] 2018-10-18 15:22
Its 100% back. 6.0.0-beta.6

**Comment by wbhob** [comment] 2018-10-19 16:26
Locking this issue, please continue conversation in #74
